services:

  primary:
    image: pg-17
    hostname: db-primary
    ports:
      - "5432:5432"
    networks:
      - db
    volumes:
      - .:/work
      - db-archive:/mnt/archive
    configs:
      - source: db-primary
        target: /var/lib/postgresql/pg-replication-primary.conf
      - source: pg-hba-extras
        target: /var/lib/postgresql/pg-hba-extras.conf

  replica:
    image: pg-17
    hostname: db-replica
    ports:
      - "5433:5432"
    networks:
      - db
    volumes:
      - .:/work
      - db-archive:/mnt/archive
    configs:
#     - source: db-replica
#       target: /var/lib/postgresql/pg-replication-replica.conf
      - source: pg-streaming-replica
        target: /var/lib/postgresql/pg-replication-replica.conf
      - source: standby-signal
        target: /var/lib/postgresql/standby.signal
    depends_on:
      - primary

volumes:
  db-archive:
    driver: local

configs:
  # log shipping
  db-primary:
    file: ./docker/pg-replication-primary.conf
  db-replica:
    file: ./docker/pg-replication-replica.conf
  standby-signal:
    file: /dev/null

  # streaming
  pg-streaming-replica:
    file: ./docker/pg-streaming-replica.conf
  pg-hba-extras:
    file: ./docker/pg-hba-extras.conf

networks:
  db: {}
